In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:

df = sns.load_dataset('iris')

In [3]:

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:

encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [5]:

df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:

df = df[['sepal_length','petal_length','species']]

In [7]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [8]:

X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [9]:

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [11]:
import sklearn
print(sklearn.__version__)

1.8.0

In [13]:
from sklearn.linear_model import LogisticRegression
print(LogisticRegression)

<class 'sklearn.linear_model._logistic.LogisticRegression'>

In [15]:
clf = LogisticRegression(solver='lbfgs')

In [16]:

y_pred = clf.predict(X_test)

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.