In [1]:
import numpy as np
import pandas as pd

In [5]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [10]:
#converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
441 2019-02-15        2906       16       2       2019
574 2019-11-13        5639       25       4       2019
363 2019-01-09        6860       26       1       2019
425 2018-10-09        4944       26       9       2018
569 2019-02-18        5795       14       4       2019

In [15]:
date['date_month']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
647 2018-09-05        6556       23       2          9           9
232 2019-01-08         666       23       9          1           1
575 2018-09-27        4627       26       1          9           9
197 2018-09-14        3440       26     101          9           9
977 2018-12-14         460       18       4         12          12

In [16]:
date['date_month_name']=date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
484,2019-02-09,2123,16,1,2,2,February
224,2019-11-20,4495,28,2,11,11,November
723,2018-12-07,2879,3,1,12,12,December
150,2019-07-10,7478,24,9,7,7,July
826,2018-09-22,944,28,1,9,9,September

In [23]:
date['date_day']=date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_name
450,2018-09-30,3532,25,5,9,9,September,30,6,Sunday
604,2019-12-05,5708,26,1,12,12,December,5,3,Thursday
346,2018-11-10,2215,16,1,11,11,November,10,5,Saturday
270,2019-11-23,704,13,10,11,11,November,23,5,Saturday
410,2019-05-17,6309,29,2,5,5,May,17,4,Friday

In [19]:
date['date_dow']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,12,12,December,10,1
1,2018-08-15,3646,14,157,8,8,August,15,2
2,2018-10-23,1859,25,1,10,10,October,23,1
3,2019-08-17,7292,25,1,8,8,August,17,5
4,2019-01-06,4344,25,3,1,1,January,6,6

In [21]:
date['date_name']=date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_name
345,2018-07-26,6857,18,61,7,7,July,26,3,Thursday
389,2018-10-25,2911,26,2,10,10,October,25,3,Thursday
625,2018-10-05,5849,26,5,10,10,October,5,4,Friday
830,2019-03-14,3047,4,4,3,3,March,14,3,Thursday
640,2018-11-03,3161,21,1,11,11,November,3,5,Saturday

In [26]:
#is weekend

date['date_is_weekend']=np.where(date['date_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_name,date_is_weekend
0,2019-12-10,12,12,December,10,1,Tuesday,0
1,2018-08-15,8,8,August,15,2,Wednesday,0
2,2018-10-23,10,10,October,23,1,Tuesday,0
3,2019-08-17,8,8,August,17,5,Saturday,1
4,2019-01-06,1,1,January,6,6,Sunday,1

In [28]:
date['date_week']=date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_name,date_is_weekend,date_week
0,2019-12-10,12,12,December,10,1,Tuesday,0,50
1,2018-08-15,8,8,August,15,2,Wednesday,0,33
2,2018-10-23,10,10,October,23,1,Tuesday,0,43
3,2019-08-17,8,8,August,17,5,Saturday,1,33
4,2019-01-06,1,1,January,6,6,Sunday,1,1

In [33]:
date['quarter']=date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_name,date_is_weekend,date_week,quarter
0,2019-12-10,12,12,December,10,1,Tuesday,0,4,4
1,2018-08-15,8,8,August,15,2,Wednesday,0,3,3
2,2018-10-23,10,10,October,23,1,Tuesday,0,4,4
3,2019-08-17,8,8,August,17,5,Saturday,1,3,3
4,2019-01-06,1,1,January,6,6,Sunday,1,1,1

In [34]:
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,12,12,December,10,1,Tuesday,0,4,4,2
1,2018-08-15,8,8,August,15,2,Wednesday,0,3,3,2
2,2018-10-23,10,10,October,23,1,Tuesday,0,4,4,2
3,2019-08-17,8,8,August,17,5,Saturday,1,3,3,2
4,2019-01-06,1,1,January,6,6,Sunday,1,1,1,1

In [35]:
#time elapsed between dates

import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 3, 18, 5, 29, 6, 495073)

In [36]:
today-date['date']

0     2290 days 05:29:06.495073
1     2772 days 05:29:06.495073
2     2703 days 05:29:06.495073
3     2405 days 05:29:06.495073
4     2628 days 05:29:06.495073
                 ...
995   2718 days 05:29:06.495073
996   2659 days 05:29:06.495073
997   2507 days 05:29:06.495073
998   2572 days 05:29:06.495073
999   2346 days 05:29:06.495073
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
(today-date['date']).dt.days

0      2290
1      2772
2      2703
3      2405
4      2628
       ...
995    2718
996    2659
997    2507
998    2572
999    2346
Name: date, Length: 1000, dtype: int64

In [41]:
#months passed
np.round((today-date['date'])/np.timedelta64(1,'m'),0)

0      3297929.0
1      3992009.0
2      3892649.0
3      3463529.0
4      3784649.0
         ...
995    3914249.0
996    3829289.0
997    3610409.0
998    3704009.0
999    3378569.0
Name: date, Length: 1000, dtype: float64

In [42]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [46]:
time['date'] = pd.to_datetime(time['date'])
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['second']=time['date'].dt.second

In [47]:
time.head()

,date,msg,hour,min,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [48]:
#extract time part
time['time']=time['date'].dt.time
time.head()

,date,msg,hour,min,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [49]:
#time difference
today-time['date']

0     4476 days 04:39:06.495073
1     4340 days 05:49:06.495073
2     4826 days 05:08:06.495073
3     4128 days 04:58:06.495073
4     4525 days 06:18:06.495073
                 ...
995   5115 days 04:39:06.495073
996   4436 days 06:15:06.495073
997   4901 days 05:52:06.495073
998   5017 days 05:55:06.495073
999   4289 days 06:04:06.495073
Name: date, Length: 1000, dtype: timedelta64[ns]

In [50]:
#in seconds
(today-time['date'])/np.timedelta64(1,'s')

0      3.867431e+08
1      3.749969e+08
2      4.169849e+08
3      3.566771e+08
4      3.909827e+08
           ...
995    4.419527e+08
996    3.832929e+08
997    4.234675e+08
998    4.334901e+08
999    3.705914e+08
Name: date, Length: 1000, dtype: float64

In [51]:
#in minutes
(today-time['date'])/np.timedelta64(1,'m')

0      6.445719e+06
1      6.249949e+06
2      6.949748e+06
3      5.944618e+06
4      6.516378e+06
           ...
995    7.365879e+06
996    6.388215e+06
997    7.057792e+06
998    7.224835e+06
999    6.176524e+06
Name: date, Length: 1000, dtype: float64